// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyThuongPhongBan.Data;

#nullable disable

namespace QuanLyThuongPhongBan.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251201173003_init-create")]
    partial class initcreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyThuongPhongBan.Models.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("id_phong_ban");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ho_ten");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mat_khau");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten_dang_nhap");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("tb_tai_khoan", (string)null);
                });

            modelBuilder.Entity("QuanLyThuongPhongBan.Models.Entities.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("id_tai_khoan");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("hanh_dong");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("mo_ta");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("tb_nhat_ky", (string)null);
                });

            modelBuilder.Entity("QuanLyThuongPhongBan.Models.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mo_ta");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_phong_ban");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tb_phong_ban", (string)null);
                });

            modelBuilder.Entity("QuanLyThuongPhongBan.Models.Entities.ProjectBonus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ContractValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("gia_tri_hop_dong");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("Settlement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("quyet_toan");

                    b.Property<decimal>("TotalAcceptance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tong_nghiem_thu");

                    b.Property<decimal>("TotalAdjustment1Rate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tong_ti_le_dieu_chinh_dot_1");

                    b.Property<decimal>("TotalAdjustment1Value")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tong_gia_tri_dieu_chinh_dot_1");

                    b.Property<decimal>("TotalAdjustment2Rate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tong_ti_le_dieu_chinh_dot_2");

                    b.Property<decimal>("TotalAdjustment2Value")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tong_gia_tri_dieu_chinh_dot_2");

                    b.Property<decimal>("TotalDebtRecovery")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tong_thu_hoi_cong_no");

                    b.Property<decimal>("TotalProjectBonusRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tong_ti_le_thuong_du_an");

                    b.Property<decimal>("TotalProjectBonusValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tong_gia_tri_thuong_du_an");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("nam_thuong");

                    b.HasKey("Id");

                    b.ToTable("tb_thuong_du_an", (string)null);
                });

            modelBuilder.Entity("QuanLyThuongPhongBan.Models.Entities.ProjectBonusDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("hop_dong_so");

                    b.Property<decimal>("ContractRevenue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("doanh_thu_hop_dong");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_thang");

                    b.Property<decimal>("HSDA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("hsda");

                    b.Property<string>("Investor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("chu_dau_tu");

                    b.Property<decimal>("InvoicedRevenue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("doanh_thu_da_xuat_hoa_don");

                    b.Property<decimal>("KTK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("ktk");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ghi_chu");

                    b.Property<decimal>("PO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("po");

                    b.Property<decimal>("PaidAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("da_thanh_toan");

                    b.Property<int?>("ProjectBonusId")
                        .HasColumnType("int")
                        .HasColumnName("id_thuong_du_an");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("du_an");

                    b.Property<decimal>("SettlementRevenue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("doanh_thu_quyet_toan");

                    b.Property<decimal>("TTDVKT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("ttdvkt");

                    b.Property<decimal>("TVGP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tvgp");

                    b.Property<decimal>("UninvoicedRevenue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("doanh_thu_chua_xuat_hoa_don");

                    b.Property<decimal>("UnpaidAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("chua_thanh_toan");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("ProjectBonusId");

                    b.ToTable("tb_thuong_du_an_chi_tiet", (string)null);
                });

            modelBuilder.Entity("QuanLyThuongPhongBan.Models.Entities.ProjectTeamBonus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Acceptance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("nghiem_thu");

                    b.Property<decimal>("Adjustment1Rate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("ti_le_dieu_chinh_dot_1");

                    b.Property<decimal>("Adjustment1Value")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("gia_tri_dieu_chinh_dot_1");

                    b.Property<decimal>("Adjustment2Rate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("ti_le_dieu_chinh_dot_2");

                    b.Property<decimal>("Adjustment2Value")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("gia_tri_dieu_chinh_dot_2");

                    b.Property<decimal>("ContractRevenue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("doanh_thu_hop_dong");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("DebtRecovery")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("thu_hoi_cong_no");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("id_phong_ban");

                    b.Property<decimal>("InvoiceRevenue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("doanh_thu_xuat_hoa_don");

                    b.Property<int>("ProjectBonusId")
                        .HasColumnType("int")
                        .HasColumnName("id_thuong_du_an");

                    b.Property<decimal>("TotalPackageRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("ti_le_tong_goi");

                    b.Property<decimal>("TotalPackageValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("gia_tri_tong_goi");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ProjectBonusId");

                    b.ToTable("tb_thuong_dai_doan_du_an", (string)null);
                });

            modelBuilder.Entity("SmbBonus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("InvoiceOutput")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("xuat_hoa_don");

                    b.Property<string>("QuarterYear")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("quy_nam_thuong");

                    b.Property<decimal>("TotalAcceptance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tong_nghiem_thu");

                    b.Property<decimal>("TotalDebtRecovery")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tong_thu_hoi_cong_no");

                    b.Property<decimal>("TotalPhase1Rate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tong_ti_le_dot_1");

                    b.Property<decimal>("TotalPhase1Value")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tong_gia_tri_dot_1");

                    b.Property<decimal>("TotalSmbBonusRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tong_ti_le_thuong_smb");

                    b.Property<decimal>("TotalSmbBonusValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tong_gia_tri_thuong_smb");

                    b.Property<decimal>("TotalSmbValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tong_gia_tri_smb");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.ToTable("tb_thuong_smb", (string)null);
                });

            modelBuilder.Entity("SmbTeamBonus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Acceptance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("nghiem_thu");

                    b.Property<decimal>("ContractRevenue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("doanh_thu_hop_dong");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("DebtRecovery")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("thu_hoi_cong_no");

                    b.Property<decimal>("DebtRecoveryRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("ti_le_thu_hoi_cong_no");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("id_phong_ban");

                    b.Property<decimal>("InvoiceRevenue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("doanh_thu_xuat_hoa_don");

                    b.Property<decimal>("Phase1Rate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("ti_le_dot_1");

                    b.Property<decimal>("Phase1Value")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("gia_tri_dot_1");

                    b.Property<int>("SmbBonusId")
                        .HasColumnType("int")
                        .HasColumnName("id_thuong_smb");

                    b.Property<decimal>("TotalSmbRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("ti_le_tong_smb");

                    b.Property<decimal>("TotalSmbValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("gia_tri_tong_smb");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SmbBonusId");

                    b.ToTable("tb_thuong_dai_doan_smb", (string)null);
                });

            modelBuilder.Entity("QuanLyThuongPhongBan.Models.Entities.Account", b =>
                {
                    b.HasOne("QuanLyThuongPhongBan.Models.Entities.Department", "Department")
                        .WithMany("Accounts")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("QuanLyThuongPhongBan.Models.Entities.ActivityLog", b =>
                {
                    b.HasOne("QuanLyThuongPhongBan.Models.Entities.Account", "Account")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("AccountId")
                        .HasPrincipalKey("Username")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("QuanLyThuongPhongBan.Models.Entities.ProjectBonusDetail", b =>
                {
                    b.HasOne("QuanLyThuongPhongBan.Models.Entities.ProjectBonus", "ProjectBonus")
                        .WithMany("ProjectBonusDetails")
                        .HasForeignKey("ProjectBonusId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ProjectBonus");
                });

            modelBuilder.Entity("QuanLyThuongPhongBan.Models.Entities.ProjectTeamBonus", b =>
                {
                    b.HasOne("QuanLyThuongPhongBan.Models.Entities.Department", "Department")
                        .WithMany("ProjectTeamBonuses")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyThuongPhongBan.Models.Entities.ProjectBonus", "ProjectBonus")
                        .WithMany("ProjectTeamBonuses")
                        .HasForeignKey("ProjectBonusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("ProjectBonus");
                });

            modelBuilder.Entity("SmbTeamBonus", b =>
                {
                    b.HasOne("QuanLyThuongPhongBan.Models.Entities.Department", "Department")
                        .WithMany("SmbTeamBonuses")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmbBonus", "SmbBonus")
                        .WithMany("SmbTeamBonuses")
                        .HasForeignKey("SmbBonusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("SmbBonus");
                });

            modelBuilder.Entity("QuanLyThuongPhongBan.Models.Entities.Account", b =>
                {
                    b.Navigation("ActivityLogs");
                });

            modelBuilder.Entity("QuanLyThuongPhongBan.Models.Entities.Department", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("ProjectTeamBonuses");

                    b.Navigation("SmbTeamBonuses");
                });

            modelBuilder.Entity("QuanLyThuongPhongBan.Models.Entities.ProjectBonus", b =>
                {
                    b.Navigation("ProjectBonusDetails");

                    b.Navigation("ProjectTeamBonuses");
                });

            modelBuilder.Entity("SmbBonus", b =>
                {
                    b.Navigation("SmbTeamBonuses");
                });
#pragma warning restore 612, 618
        }
    }
}
